#
# AscNHalf Hook
#

# Travis language: cpp
language: cpp

install:
 - sudo apt-get install build-essential unzip make cmake zlib1g-dev libssl-dev libtool libpcre3-dev mysql-client libmysql++-dev libmysqlclient15-dev

script:
 - ./build.sh

# Only watch the master branch
branches:
  only:
    - master

# Notify if needed
notifications:
  irc:
    channels:
      - "irc.rizon.net#schumix2"
